/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ARow: typeof import('ant-design-vue/es')['Row']
    ClashLinkItem: typeof import('./src/components/ClashLinkItem.vue')['default']
  }
}
